### ISSUE TITLE
Merge off-hand damage with main-hand

### ISSUE THREAD

**Issue by Cyperino** [Justw8/NameplateSCT#12]
Hello
I was wandering if it is possible to merge the damage of spells like mutilate/ oblitare that uses off-hand.

**Comment by Justw8** [comment]
no, I do not merge damage events that are close to eachother.

**Comment by Cyperino** [comment]
I understand. I assume it can't show which one is offhand because of the same thing. Can't we put some little delay before showing the damage?

**Comment by Justw8** [comment]
That kind off defeats the purpose of the addon, as it's supposed to be a fancier way of displaying the damage numbers like blizzard does. I want to avoid as much logic as possible, otherwise you are opening a box of pandora and it will never end.

the only consideration I have is the merge damage events if they are close together.

**Comment by Cyperino** [comment]
Ok, ty for the answers ^^
